### ISSUE TITLE
ขอตัวดึง tag ID

### ISSUE THREAD

**Issue by yuyik** [VectorXz/alienworlds_acc_monitor#1]
curl -X POST "https://api.waxsweden.org/v1/chain/get_table_rows" -H "accept: */*" -H "Content-Type: application/json" -d "{\"json\":true,\"code\":\"federation\",\"scope\":\"federation\",\"table\":\"players\",\"table_key\":\"\",\"lower_bound\":\"3wjbu.wam\",\"upper_bound\":\"3wjbu.wam\",\"index_position\":1,\"key_type\":\"\",\"limit\":10,\"reverse\":false,\"show_payer\":false}"

**Comment by VectorXz** [comment]
Solved in 4e949d52e2d1dab67a84f36b89fe9db67cb2da5f
