### ISSUE TITLE
Table Total Suggestion

### ISSUE THREAD

**Issue by MattwCosta** [VectorXz/alienworlds_acc_monitor#13]
I suggest adding totals information.

Like:
Total wax staked
Total wax balance

**Comment by MattwCosta** [comment]
Something similar to this:
Or I don’t know, add a total row to the end of the table.

![image](https://user-images.githubusercontent.com/11450532/119719803-9b245a00-be3f-11eb-97dc-a82239caa324.png)

**Comment by VectorXz** [comment]
Thank you for your recommendation, I'll add that in the development plan!

**Comment by VectorXz** [comment]
Hi!
Today I just released a new version of balance summary section, hope you'll like it!

![image](https://user-images.githubusercontent.com/9075013/120068629-d034e480-c0ab-11eb-815d-38e3fbd41d48.png)
