### ISSUE TITLE
ID ใหม่ wax จะขึ้น N/A WAX

### ISSUE THREAD

**Issue by yuyik** [VectorXz/alienworlds_acc_monitor#20]
จะทำให้ยอดรวม wax ไม่ขึ้นครับ
![Screenshot_68](https://user-images.githubusercontent.com/1606894/123028150-2bd36300-d409-11eb-9c9c-213e7cf96bcf.jpg)
![Screenshot_69](https://user-images.githubusercontent.com/1606894/123028155-2d9d2680-d409-11eb-8746-b5715fec0dd1.jpg)

**Comment by VectorXz** [comment]
Fixed in f3a325a , the N/A account will not accumulate to the total wax.
