### ISSUE TITLE
Not work 

### ISSUE THREAD

**Issue by Darklightsite** [VectorXz/alienworlds_acc_monitor#8]
Need payment :(
How can we donate jour Job? 
![Screenshot_2021-05-21-04-11-49-930_com android chrome](https://user-images.githubusercontent.com/84232138/119072439-c0ead280-b9eb-11eb-9b16-231950d81c23.jpg)

**Comment by VectorXz** [comment]
Sorry for any inconvenience, since there are a lots of user requests, so the web host provider temporarily disabled our service since the bandwidth reaches quota.
I'm looking for migrating to another provider, stay tune!
